### ISSUE TITLE
missing operators *, / and %

### ISSUE THREAD

**Issue by AndyOGo** [shellscape/postcss-values-parser#58]
First thanks for this awesome package, I just started using it.

* Node Version: `v6.12.3`
* NPM Version: `3.10.10`
* postcss-values-parser Version: `2.0.0`

This issue is regarding a problem with:
- [x] Standard CSS [calc `+`, `-`, `*` and `/`](https://developer.mozilla.org/en-US/docs/Web/CSS/calc#Syntax)
- [x] LESS supports [math options](http://lesscss.org/usage/#less-options-math) and as such all possible ECMAScript operators
- [x] SCSS supports [operators like `+`, `-`, `*`, `/`, and `%`](https://sass-lang.com/guide#topic-8)
- [x] SASS supports [operators like `+`, `-`, `*`, `/`, and `%`](https://sass-lang.com/guide#topic-8)

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```css
// offending or problematic css
.foo { margin: 2 * 10 }; 
.foo { margin: 2 / 10 }; 
.foo { margin: 10 % modulo }; 

// and using just those operators does not throw
.foo { margin: * }; 
.foo { margin: / };
.foo { margin: % };

// But for + and - it does throw
.foo { margin: + }; 
.foo { margin: - };
```

### Expected Behavior

`*` multiply, `/` divide and `%` modulo should be parsed as `operators` too.
And they should throw according to the same rules of `+` add and `-` subtract.

### Actual Behavior

Not detected as operators and do not throw based on same rules like for add and subtract.

### How can we reproduce the behavior?

See above CSS and this PR https://github.com/shellscape/postcss-values-parser/pull/59
