### ISSUE TITLE
Prettier format url path with number incorrectly

### ISSUE THREAD

**Issue by jasonxia23** [shellscape/postcss-values-parser#62]
* Node Version:
* NPM Version:
* postcss-values-parser Version: 1.5.0

This issue is regarding a problem with:
- [x] Standard CSS
- [ ] LESS
- [ ] SCSS
- [ ] SASS

If you have a large amount of code to share which demonstrates the problem you're experiencing, please provide a link to your
repository rather than pasting code. Otherwise, please paste relevant short snippets below.

```css
// offending or problematic css
body {
  background: url(http://123.example.com);
}
```

### Expected Behavior

```css
body {
  background: url(http://123.example.com);
}
```

### Actual Behavior

```css
body {
  background: url(http://123example.com);
}
```

### How can we reproduce the behavior?

[Playground link](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEAjCATAngAmAHShx1QEMwBrAcwCcIBXKDJHemgGwAoALGGAByQB6IQEYATAGYAdHAAepALb92caZEUBKANyEAviAA0ICPxgBLaAGdkoUjToB3AAr2ENlKQBuEcxiNoNOQUcDAAyvzk5lBUyDA09HDGvIrsAOrc5vBWkWBwYe5Z5l5ZWMjgVjbG0VZwNDDOQVSKpMgAZqTstcYAVlZyAEJBlKFhSnAAMtFw7Z3dIH1yYdFUqgCK9BDws11JIJE0tTTlYJUB-DTRMGl+MNzIABwADMYXELVpQfzlF3BHXjNjDQ4ABHejmYGNUjNVpIDq7Yy1RTmOIJPZWFbrTbbOFzPYwUioG4YO7IcTGeKkczsFYAYQgiha5Sg0EBIHotQAKoSPPDano9EA)

See also https://github.com/prettier/prettier/issues/5654
