### ISSUE TITLE
add isVar to func to  mark CSS variables usage

### ISSUE THREAD

**Issue by AndyOGo** [shellscape/postcss-values-parser#82]
### Feature Use Case

```css
// declaring a csutomproperty
element {
  --main-bg-color: brown;
}

// Using the custom property:
element {
  background-color: var(--main-bg-color);
}
```

https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties
https://drafts.csswg.org/css-variables/#defining-variables

### Feature Proposal

I would propose to extend the **Func** node with `isVar` to mark `var()` calls related to using variables:
https://developer.mozilla.org/en-US/docs/Web/CSS/var
https://drafts.csswg.org/css-variables/#using-variables
